### ISSUE TITLE
-O3 PerlIO_flush problem (testc.sh 91)

### ISSUE THREAD

**Issue by rurban** [rurban/perl-compiler#120]
Original [issue 118](https://code.google.com/p/perl-compiler/issues/detail?id=118) created by rurban on 2013-02-05T17:50:30.000Z:

<b>What steps will reproduce the problem?</b>
t/testc.sh -O3 91
vs.
t/testc.sh -O0 91

print &quot;ok&quot; is executed in both cases, just with -O3 the final my_fflush_all() at perl_destruct() doesn't flush STDOUT.

Observation:
With -O3 there are multiple calls to PerlIO_close() and PerlIO_flush() during parse and run-time, which does not happen with -O0.

2x:
#&nbsp;0  Perl_PerlIO_flush (f=0x823b50) at perlio.c:1750
#&nbsp;1  0x00007ffff7cbfa62 in PerlIOBase_close (f=0x823b50) at perlio.c:2238
#&nbsp;2  0x00007ffff7cc30cd in PerlIOBuf_close (f=0x823b50) at perlio.c:4262
#&nbsp;3  0x00007ffff7cbe022 in PerlIO__close (f=0x823b50) at perlio.c:1503
#&nbsp;4  0x00007ffff7cbe05c in Perl_PerlIO_close (f=0x823b50) at perlio.c:1516
#&nbsp;5  0x00007ffff79fd9cc in Perl_lex_next_chunk (flags=0) at toke.c:1277
#&nbsp;6  0x00007ffff7a0e858 in Perl_yylex () at toke.c:4777
#&nbsp;7  0x00007ffff7a3ce84 in Perl_yyparse (gramtype=258) at perly.c:434
#&nbsp;8  0x00007ffff79c57b2 in S_parse_body (env=0x7fffffffe718, xsinit=0x62862c &lt;xs_init&gt;) at perl.c:2194
#&nbsp;9  0x00007ffff79c39b8 in perl_parse (my_perl=0x814010, xsinit=0x62862c &lt;xs_init&gt;, argc=4, argv=0x81eb60, env=0x7fffffffe718)
    at perl.c:1613

(gdb) bt
#&nbsp;0  Perl_PerlIO_flush (f=0x823b70) at perlio.c:1750
#&nbsp;1  0x00007ffff7afca55 in Perl_pp_print () at pp_hot.c:790
#&nbsp;2  0x00007ffff7a9d5c3 in Perl_runops_debug () at dump.c:2266
#&nbsp;3  0x00007ffff79c6898 in S_run_body (oldscope=1) at perl.c:2350
#&nbsp;4  0x00007ffff79c5b55 in perl_run (my_perl=0x814010) at perl.c:2268
#&nbsp;5  0x00000000006293f0 in main (argc=1, argv=0x7fffffffe708, env=0x7fffffffe718) at ccode91_o3.c:54882

(gdb) bt
#&nbsp;0  Perl_PerlIO_flush (f=0x981d50) at perlio.c:1750
#&nbsp;1  0x00007ffff7cc2795 in PerlIOBuf_flush (f=0x823b70) at perlio.c:4006
#&nbsp;2  0x00007ffff7cbecb0 in Perl_PerlIO_flush (f=0x823b70) at perlio.c:1755
#&nbsp;3  0x00007ffff7afca55 in Perl_pp_print () at pp_hot.c:790
#&nbsp;4  0x00007ffff7a9d5c3 in Perl_runops_debug () at dump.c:2266
#&nbsp;5  0x00007ffff79c6898 in S_run_body (oldscope=1) at perl.c:2350
#&nbsp;6  0x00007ffff79c5b55 in perl_run (my_perl=0x814010) at perl.c:2268
#&nbsp;7  0x00000000006293f0 in main (argc=1, argv=0x7fffffffe708, env=0x7fffffffe718) at ccode91_o3.c:54882

vs 
(gdb) bt
#&nbsp;0  Perl_PerlIO_flush (f=0x0) at perlio.c:1750
#&nbsp;1  0x00007ffff7aa7edc in Perl_my_fflush_all () at util.c:3817
#&nbsp;2  0x00000000006285fc in fast_perl_destruct (my_perl=0x814010) at ccode91_o3.c:54706
#&nbsp;3  0x0000000000629405 in main (argc=1, argv=0x7fffffffe708, env=0x7fffffffe718) at ccode91_o3.c:54883

**Comment by toddr** [comment]
This passes on This branch https://github.com/CpanelInc/perl-compiler/tree/cm522
t/testc.sh -O3 91

**Comment by toddr** [comment]
This actually passes on command line with perlcc or testc.sh -q. There's a bug with testc.sh causing this to fail.

**Comment by atoomic** [comment]
This is a segfault which is only triggered when enabling debug...
when saving an AV, we are using $av->flagspv and earlier flag a PADLIST with @ISA AV...
we should not call this method on a PADLIST

```diff
diff --git a/lib/B/C.pm b/lib/B/C.pm
index ee7bf92..44ddb2e 100644
--- a/lib/B/C.pm
+++ b/lib/B/C.pm
@@ -4980,7 +4980,9 @@ sub B::AV::save {
   }

   my ($magic, $av_index) = ('');
-  $svsect->debug($fullname, $av->flagspv) if $debug{flags};
+  # a PADLIST is tag as an AV but does not have flagspv
+  #   another option would be to define it:  *B::PADLIST::flagspv = sub { 0 }
+  $svsect->debug($fullname, ref $av eq 'B::PADLIST' ? 0 : $av->flagspv) if $debug{flags};
   if (!$ispadlist and !$ispadnamelist) {
     my $sv_ix = $svsect->index;
     $av_index = $xpvavsect->index;

**Comment by toddr** [comment]
@rurban is working on an alternate fix in B::Flags. Keeping this open until B::Flags 0.15 resolves this.

**Comment by toddr** [comment]
using B::Flags 0.15 resolves this issue. Closing ticket.
