### ISSUE TITLE
$! does not retrieve the current value of the C errno integer variable wth invalid file descriptor

### ISSUE THREAD

**Issue by rurban** [rurban/perl-compiler#152]
Original [issue 150](https://code.google.com/p/perl-compiler/issues/detail?id=150) created by klafkoff on 2013-11-05T21:23:21.000Z:

<b>What steps will reproduce the problem?</b>

use Errno;
$! = 0; 
no warnings &quot;unopened&quot;; 
print NONEXISTENT &quot;foo&quot;; 
print &quot;ok&quot; if ($! == &amp;Errno::EBADF);

<b>What is the expected output? What do you see instead?</b>

Expected: 'ok'
Got: ''

<b>What version of the product are you using? On what operating system?</b>

5.14 - Cent 6 - 64 bit

<b>Please provide any additional information below.</b>

**Comment by toddr** [comment]
This issue was opened by kyle. It's been resolved.
