### ISSUE TITLE
smartmatch subrefs

### ISSUE THREAD

**Issue by rurban** [rurban/perl-compiler#181]
Original [issue 179](https://code.google.com/p/perl-compiler/issues/detail?id=179) created by atoomic on 2013-11-08T20:51:14.000Z:

<b>What steps will reproduce the problem?</b>
compile  the smartmatch script provided bellow
1. /usr/local/cpanel/3rdparty/perl/514/bin/perl -MO=-qq,C,-O2,-fno-warnings,-fno-fold,-oop/smartmatch.c op/smartmatch.t
2. /usr/local/cpanel/3rdparty/perl/514/bin/perl ../../script/cc_harness -q  op/smartmatch.c -o op/smartmatch.bin
3. ./op/smartmatch.bin

```perl
{
    package Foo;
    sub new { bless {} }
}

package main;

our $foo = Foo->new;
our $bar = $foor; # required to generate the wrong behavior

my $match = eval '$foo ~~ undef' ? 1 : 0;
print "match ? $match\n";
```

<b>What is the expected output? What do you see instead?</b>

expect: match ? 0
got: match ? 1

<b>What perl version are you using? Threaded? -DDEBUGGING? On what operating</b>
<b>system?</b>

perl 5.14.3 on centos 6.4 32 bits

<b>Please provide any additional information below.</b>

**Comment by toddr** [comment]
This passes in both of the reported ways on master now. This bug is resolved.
