### ISSUE TITLE
B::C Problem running executable on another node without perl installation

### ISSUE THREAD

**Issue by sten22** [rurban/perl-compiler#197]
## environment
debian 7 x64, I've tried 5.14.2, 5.18.4 and 5.20.2

## test script
any script, which use XS:
```perl
use Template;
use Template::Stash::XS;

Template->new->process(\'[% a + b _ "\n" %]', {a => 1, b => 2});
```

## expected output
```
root@d6151e0bcd3c:/home/ap-bc# ./template 
3
```
## output on another machine without perl installed
```
#5.14.2
root@ebee7a8687f7:/home/ap-bc# ./template 
Can't locate loadable object for module B in @INC (@INC contains: /etc/perl /usr/local/lib/site_perl /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at /usr/lib/perl/5.14/B.pm line 0
Segmentation fault

#5.20.2
root@ebee7a8687f7:/home/ap-bc# ./template 
Undefined subroutine &Carp::downgrade called at /root/perl5/perlbrew/perls/perl-5.20.2/lib/5.20.2/Carp.pm line 285.
Segmentation fault

#5.18.4
root@ebee7a8687f7:/home/ap-bc# ./template 
Undefined subroutine &Carp::downgrade called at /root/perl5/perlbrew/perls/perl-5.18.4/lib/5.18.4/Carp.pm line 201.
Segmentation fault

```

**Comment by rurban** [comment]
*perlcc* compiled executables still need several shared libs, some at load-time (check with ldd) and some at run-time. check the verbose output.
using *--static-xs* will statically link the detected run-time XS libs on systems which allow this (non-darwin).

**Comment by sten22** [comment]
what is best way to ship libs with executable?

**Comment by rurban** [comment]
find them and ship them.
use a perl with a static libperl.a to have one problem less.
find the static ones with ldd, and the dynamic ones with @DynaLoader::dl_modules.

**Comment by sten22** [comment]
thanks!
