### ISSUE TITLE
Missing XSLoader with Moo “Not a CODE reference” w/ a specific 5.14

### ISSUE THREAD

**Issue by drmuey** [rurban/perl-compiler#201]
Hey Reini!

As you requested here is the github issue to track the problem originally reported at https://rt.cpan.org/Public/Bug/Display.html?id=104854 (reproducable via the details in that RT).

This was the one we looked at together at YAPC::NA 2015 which you determined was an issue specific to the 5.14 we were using (but not all 5.14s).

Thanks!

**Comment by rurban** [comment]
Example:
'use tmp::MyMoo;print Moo->VERSION;'
with 
    # cat tmp/XYZ.pm 
    package tmp::XYZ;
    use strict;
    use warnings;
    use tmp::MyMoo;
    1;

and

    # cat tmp/MyMoo.pm 
    package tmp::MyMoo;
    use Moo; # does strict and warnings
    has foo => ("is" => "rw");
    1;

The problem is wrong XSLoader detection, so not really Moo specific.

**Comment by toddr** [comment]
@drmuey This currently works for perl 5.22 on master. If the attached code is not what you want fixed, please re-open this case with an explicit one liner that you need to work.

```
$>perlcc -r -e 'package tmp::MyMoo; use Moo;  has foo => ("is" => "rw"); package tmp::XYZ; use strict; use warnings; use tmp::MyMoo;package main; print Moo->VERSION . "ok\n" '
2.000002ok
```
