### ISSUE TITLE
B::C doesn't work on simple perl 5.22 program

### ISSUE THREAD

**Issue by toddr** [rurban/perl-compiler#204]
$> perl522  -MO=C -E'print "hello world\n"'
Can't locate object method "save" via package "B::PADNAMELIST" at /perl/522/lib/perl5/lib/i386-linux-64int/B/C.pm line 4544.
CHECK failed--call queue aborted.

**Comment by toddr** [comment]
perldelta for 5.22.0

B::PMOP now provides a pmregexp method returning a B::REGEXP object. Two new classes, B::PADNAME and B::PADNAMELIST, have been introduced.

The PADNAME and PADNAMELIST types are now separate types, and no longer simply aliases for SV and AV. [perl #123223].

Pad names are now always UTF-8. The PadnameUTF8 macro always returns true. Previously, this was effectively the case already, but any support for two different internal representations of pad names has now been removed.

**Comment by rurban** [comment]
Yes, 5.22 is not yet supported. The PADNAME changes are trivial, I already did that for B::Generate. There are much harder parts I'm working on
