### ISSUE TITLE
get_cv with utf8 => get_cvn_flags

### ISSUE THREAD

**Issue by rurban** [rurban/perl-compiler#205]
With utf8 cv names we have to use get_cvn_flags
Repro: e.g. t/mro/basic_04_dfs_utf8.t

**Comment by toddr** [comment]
CORE/mro/basic_01_c3_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/basic_01_c3_utf8.t PLAN    TODO: Malformed UTF-8. Looks like B::C makes everything UTF8 when 1 thing is compiled that way?
CORE/mro/basic_01_dfs_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/basic_01_dfs_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/basic_02_c3_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/basic_02_c3_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/basic_02_dfs_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/basic_02_dfs_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/basic_03_c3_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/basic_03_c3_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/basic_03_dfs_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/basic_03_dfs_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/basic_04_c3_utf8.t TESTS TODO: Malformed UTF-8.
CORE/mro/basic_04_dfs_utf8.t TESTS TODO: Malformed UTF-8.
CORE/mro/basic_04_dfs_utf8.t TESTS TODO: Malformed UTF-8.
CORE/mro/basic_05_c3_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/basic_05_c3_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/basic_05_dfs_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/basic_05_dfs_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/basic_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/complex_c3_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/complex_dfs_utf8.t TESTS TODO: Malformed UTF-8.
CORE/mro/next_inanon_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/next_ineval_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/next_method_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/next_NEXT_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/next_skip_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/overload_c3_utf8.t PLAN TODO: Malformed UTF-8.
CORE/mro/vulcan_c3_utf8.t TESTS TODO: Malformed UTF-8.
CORE/mro/vulcan_dfs_utf8.t TESTS TODO: Malformed UTF-8.
CORE/uni/universal.t      PLAN      TODO: Malformed UTF-8 character (unexpected non-continuation byte 0x5c, immediately after start byte 0xc3).

**Comment by rurban** [comment]
Fixed with commit 953ef84b928da6f03f73518b74c56f5919622f23
Author: Reini Urban rurban@cpanel.net
Date: Mon Sep 21 15:40:32 2015 -0500

C: utf8 GVs GH#206

abstract gv_fetchpvn() and get_cv()
for easier support of utf8 symbol and CV names.
use the faster n_flags variant if available.

But easy `t/testc.sh` testcases missing

**Comment by toddr** [comment]
Reported as fixed and other issues those tests are reported in other issues.
