### ISSUE TITLE
gv_fetchpv => gv_fetchpvn_flags for utf8 names

### ISSUE THREAD

**Issue by rurban** [rurban/perl-compiler#206]
Similar to #205 
Fails on utf8 symbol names

**Comment by rurban** [comment]
Fixed with commit 953ef84b928da6f03f73518b74c56f5919622f23
Author: Reini Urban <rurban@cpanel.net>
Date:   Mon Sep 21 15:40:32 2015 -0500

    C: utf8 GVs GH#206

    abstract gv_fetchpvn() and get_cv()
    for easier support of utf8 symbol and CV names.
    use the faster n_flags variant if available.

But easy `t/testc.sh` testcases missing

**Comment by toddr** [comment]
@rurban I don't see anything actionable here. Can we close this? If not, what perl code will show this issue?

**Comment by rurban** [comment]
We still don't have a testcase for utf8 symbols. `t/issue206.t`
