### ISSUE TITLE
Cannot use a format using a scalar

### ISSUE THREAD

**Issue by atoomic** [rurban/perl-compiler#216]
Context:
- perl 5.20.2
- B::C using bc522 with HEAD @734e776 ( cannot use 23016e1 with 5.20 )

Cannot use a format using a scalar
````
> cat format.t
#!/bin/env perl
my $x = "ok";
format A_FORMAT =
@<<<<<<<
$x
.

*STDOUT = *A_FORMAT{FORMAT};
write;
> perl format.t
ok
> perlcc -r format.t
> #  nothing on stdout
````

Note that if you replace $x by ok in the format pattern, then it passes

**Comment by rurban** [comment]
I believe this is one of the google code tickets which got not merged yet. It got stuck in the issue importer.

**Comment by toddr** [comment]
This now passes on -O3 and -O0
