### ISSUE TITLE
STDOUT->autoflush(1) should survive in perl520+

### ISSUE THREAD

**Issue by atoomic** [rurban/perl-compiler#218]
Env:
perl 5.20.2
B::C using bc522 with HEAD @734e776 ( cannot use 23016e1 with 5.20 )

Steps to reproduce
````
> perl -e 'STDOUT->autoflush(1); print qq{ok\n}'
ok
> perlcc -r -e 'STDOUT->autoflush(1); print qq{ok\n}'
````

**Comment by rurban** [comment]
Did this work in 5.14?

**Comment by atoomic** [comment]
yes this is not something new and was working in 5.14, seems like a regression

**Comment by toddr** [comment]
This now passes.
