### ISSUE TITLE
length unpack *a probably wrong

### ISSUE THREAD

**Issue by toddr** [rurban/perl-compiler#244]
It is likely that most of these are wrong. git grep length lib

We discussed an audit might be needed.

Notes from discussions:
* $cur vs $len (sometimes 0 sometimes has a value)
* xpvsect()->add( sprintf( "Nullhv, {0}, %u, {%u}", $cur, $len ) );
* STRLEN      xpv_cur;        /* length of svu_pv as a C string */
* (UNION) STRLEN  xpvlenu_len;    /* allocated size */
* in B::C::save_pv_or_rv
* $cur = length( pack "a*", $pv );

**Comment by rurban** [comment]
Fixed with commit d6d3d80201d91c1479b9860fc89efbe7ee16cf25 ?

    C: improvements per suggestion toddr+atoomic

    solidify utf8 and length. add more section comments.
    add testc test for GH #238.

**Comment by rurban** [comment]
I only left pack "a*" in right before split // for lexwarn, because this is the best todo there.
All others should be gone. The len=0 magic for static strings is ok.

**Comment by toddr** [comment]
These issues appear to be resolved.

```
$>git grep unpack lib/B/C.pm 
lib/B/C.pm:      my ($iv) = unpack($t, $pv); # unsigned longsize
lib/B/C.pm:      my $pmop_ptr = unpack("J", $mg->PTR);
```
