### ISSUE TITLE
Tie::Hash::NamedCapture linked to unnecessarily.

### ISSUE THREAD

**Issue by toddr** [rurban/perl-compiler#247]
$>\rm a.out; perlcc -O3 --staticxs -e 'package Tie::Hash; print Tie::Hash::foo() . "\n"'; ldd a.out 2>&1|grep Named 
rm: cannot remove `a.out': No such file or directory
/usr/local/cpanel/3rdparty/perl/522-debug/bin/perlcc: Unexpected compiler output
[WARNING] skip SvSTASH for overloaded HV %Errno:: flags=0x3280000c
 [WARNING] unknown (HV*)&sv_list[990] found in @static_free
	/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/auto/Tie/Hash/NamedCapture/NamedCapture.so (0x006b5000)

**Comment by toddr** [comment]
Even simpler:

$>\rm a.out; perlcc -O3 --staticxs -e ' print Tie::foo() . "\n"'; ldd a.out 2>&1|grep Named  
/usr/local/cpanel/3rdparty/perl/522-debug/bin/perlcc: Unexpected compiler output
[WARNING] skip SvSTASH for overloaded HV %Errno:: flags=0x3280000c
 [WARNING] unknown (HV*)&sv_list[990] found in @static_free
	/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/auto/Tie/Hash/NamedCapture/NamedCapture.so (0x00f5a000)

**Comment by toddr** [comment]
So the act of looking at the symbol triggers T:H:NC to load

$>perl -MB -E'my $full = q{*main::+}; my $ref = B::svref_2object(\*$full); print $INC{"Tie/Hash/NamedCapture.pm"} . "\n"'
/usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/5.22.0/i386-linux-debug-64int/Tie/Hash/NamedCapture.pm

**Comment by toddr** [comment]
What I don't know is why accessing a package with "Tie" in it is the only place this happens.

**Comment by toddr** [comment]
This fixes it.

diff --git a/lib/B/C.pm b/lib/B/C.pm
index 051e2a8..e933c32 100644
--- a/lib/B/C.pm
+++ b/lib/B/C.pm
@@ -6757,7 +6757,7 @@ sub walksymtable {
   my ($symref, $method, $recurse, $prefix) = @_;
   my ($sym, $ref, $fullname);
   $prefix = '' unless defined $prefix;
-  foreach my $sym ( sort keys %$symref ) {
+  foreach my $sym ( reverse sort keys %$symref ) {
     no strict 'refs';
     $ref = $symref->{$sym};
     $fullname = "*main::".$prefix.$sym;

**Comment by toddr** [comment]
The act of walking the symtable and hitting all the $[-!+], etc. sigils will force perl autoloading. So if we simply walk the symbol tables first before hitting the GVs in main, we can work around this problem. But overall I think the approach here needs to be questioned.

**Comment by rurban** [comment]
When looking at those 4 magic symbols we need to skip the TIEHASH magic to force this package, I think.

**Comment by toddr** [comment]
Reini applied this fix so closing issue. 

NOTE: cm522 shows this to have broken as a result  but I'm inclined to treat that as a separate issue.

op/split_unicode.t          SIG      Exit signal is 11 SEGV -- broken by the reverse sort fix for Tie::Hash::NamedCapture

**Comment by rurban** [comment]
Note that I have now several perl5.14 regressions:
```
t/C-COMPILED/CORE--op--magic-27839.t             (Wstat: 512 Tests: 23 Failed: 2)
  Failed tests:  4, 14
  Non-zero exit status: 2
t/C-COMPILED/CORE--op--local.t                   (Wstat: 2048 Tests: 23 Failed: 8)
  Failed tests:  8, 10-12, 18, 20-22
  Non-zero exit status: 8
t/C-COMPILED/CORE--op--magic.t                   (Wstat: 1536 Tests: 23 Failed: 6)
  Failed tests:  8-9, 12, 18-19, 22
  Non-zero exit status: 6
t/C-COMPILED/CORE--op--taint==BC-288.t           (Wstat: 0 Tests: 23 Failed: 0)
  TODO passed:   4-7, 13-17, 23
t/C-COMPILED/CORE--re--pat_re_eval==SIG-332.t    (Wstat: 0 Tests: 23 Failed: 0)
  TODO passed:   7, 17
t/C-COMPILED/CORE--re--reg_namedcapture.t        (Wstat: 768 Tests: 23 Failed: 3)
  Failed tests:  7-8, 12
  Non-zero exit status: 3
```
