### ISSUE TITLE
Cannot use Unicode::UC::prop_invmap in compiled code

### ISSUE THREAD

**Issue by atoomic** [rurban/perl-compiler#253]
ENV: perl 5.22 with debug enabled

This needs a deeper investigation to find the root cause of this issue,
which might be a known bug

Unicode::UCD is a CORE module

perl
````
> perl -e 'use Unicode::UCD q/prop_invmap/; my @list = prop_invmap("Uppercase_Mapping"); print qq/ok\n/'
ok
```

perlcc
```
> perlcc -e 'use Unicode::UCD q/prop_invmap/; my @list = prop_invmap("Uppercase_Mapping"); print qq/ok\n/'; ./a.out
zsh: segmentation fault  ./a.out
````

**Comment by rurban** [comment]
This is a new datatype I thought we wont need. Est. 2d

**Comment by toddr** [comment]
./t/testc.sh 253

**Comment by rurban** [comment]
For now crashes with the same SWASHNEW problems, as #273

**Comment by toddr** [comment]
Dupe. Closing.

**Comment by atoomic** [comment]
this is fixed with current work from swashnew-273 branch
