### ISSUE TITLE
Nick's -fconst-cop-strings and -fconst-sharedhek-strings optims

### ISSUE THREAD

**Issue by toddr** [rurban/perl-compiler#262]
Add support for shared HEK strings using constpv - https://github.com/toddr/perl-compiler/commit/e7e01f7108675069ed59b4c04c6887360b71e690

Add option to do constpv in B::COP::save. https://github.com/toddr/perl-compiler/commit/13eb9eb1dc5ebddcf871c84c7ce9e6a44a396930

**Comment by rurban** [comment]
gcc already merges all string constants. -fconst-sharedhek-strings is not needed.

-fconst-cop-strings is not needed anymore with the new compiler, as our stashes are now shared, and not re-initialized.
