### ISSUE TITLE
Segfault when copying STDOUT stash

### ISSUE THREAD

**Issue by atoomic** [rurban/perl-compiler#270]
tested with perl 5.22 

````
> perl -e '*x = *STDOUT; print {*x{IO}} "ok\n";'
ok
> rm -f a.out; perlcc -e '*x = *STDOUT; print {*x{IO}} "ok\n";'; ./a.out
Segmentation fault
````

**Comment by atoomic** [comment]
````
Program received signal SIGSEGV, Segmentation fault.
0x00356d4e in S_rv2gv (sv=0x8061a2c, vivify_sv=false, strict=false, noinit=false) at pp.c:212
212		if (SvAMAGIC(sv)) {
````

**Comment by toddr** [comment]
Still bisecting but I notice this one as I'm down to 75 commits:

commit 54c554f38309fa055396f28507f661ae9fbdde5e
Author: Father Chrysostomos <sprout@cpan.org>
Date:   Fri May 18 09:25:26 2012 -0700

    sv.h: define SvAMAGIC in terms of HvAMAGIC

commit 9299023c08583d1430e423584af75641cf0e1513
Author: Father Chrysostomos <sprout@cpan.org>
Date:   Fri May 18 08:52:02 2012 -0700

    sv.h: Turn off AMAGIC flag in Gv_AMG

**Comment by toddr** [comment]
This issue is no longer present.

$>./t/testc.sh -q 270
./ccode270 PASS ./ccode270 '*x = *STDOUT; print {*x{IO}} "ok\n";' => 'ok'
./ccode270_o1 PASS ./ccode270_o1 => 'ok'
./ccode270_o2 PASS ./ccode270_o2 => 'ok'
./ccode270_o3 PASS ./ccode270_o3 => 'ok'
