### ISSUE TITLE
5.22: curpad_name stored as PVMG not as PADNAME

### ISSUE THREAD

**Issue by rurban** [rurban/perl-compiler#272]
with flags 0x604407. B::Flags correctly identifies it as PADNAME.
Looks like a B bug.
This leads with test 219 to "Errno" stored as "&sv_list[629]"

**Comment by toddr** [comment]
@rurban are you saying this test is the issue? If not what code causes this problem?
./t/testc.sh -q 219

**Comment by toddr** [comment]
This appears to have been the bug which now passes with perlcc:

perlcc -r -e 'my (%b,%h); BEGIN { %b=(1..8);@a=(1,2,3,4); %h=(1=>2,3=>4) } $i=0; my $l=-1; print $h->{$b->{3}},$h->{$a[-1]},$a[$i],$a[$l],$h{3}'
144
