### ISSUE TITLE
setting mro 'c3' doesn't work for utf8 packages.

### ISSUE THREAD

**Issue by toddr** [rurban/perl-compiler#285]
Program:
```perl
#!./perl

use utf8;
binmode STDOUT, ':utf8';

package Ｄiᚪၚd_A;
sub hèllò { 'Ｄiᚪၚd_A::hèllò' }

package Ｄiᚪၚd_B;
use base 'Ｄiᚪၚd_A';

package Ｄiᚪၚd_C;
use base 'Ｄiᚪၚd_A';     
    
sub hèllò { 'Ｄiᚪၚd_C::hèllò' }

package Ｄiᚪၚd_D;
use base ('Ｄiᚪၚd_B', 'Ｄiᚪၚd_C');
use mro 'c3';

package main;
my $got = mro::get_linear_isa('Ｄiᚪၚd_D');
$got->[3] eq 'Ｄiᚪၚd_A' and print "ok\n";
$got->[2] eq 'Ｄiᚪၚd_C' and print "ok\n";
```

perlcc -r  test.pl returns nothing.

**Comment by toddr** [comment]
So I suspected the issue was related to this line of code found in 3 places:
```perl
$init->add_eval('mro::set_mro($package, "c3");');
```

My suspicion was that the eval wasn't working right for UTF8 strings in 5.22

So I patched B::C to use the MRO XS code instead. NOTE: this has to be done  in init2 since mro has to bootstrap c3 in its XS init before you can set mro to c3.

I also determined that in the above code, the Ｄiᚪၚd_D package stash was never getting saved I suspect this might be distracting you in #219 and can be resolved if you find a way to assure the package is marked used.

I noticed this code which seems to mark a package used but prevent it from saving its stash?
```perl
         unless ( $B::C::dumped_package{$package} ) {
            $B::C::dumped_package{$package} = 1;
             mark_package( $package, 1 );
      }

```

**Comment by toddr** [comment]
Applying my patch gets these tests working:

mro/basic_01_c3_utf8.t       TESTS     some tests are now failing
mro/basic_02_c3_utf8.t       TESTS     some tests are now failing
mro/basic_03_c3_utf8.t       TESTS     some tests are now failing
mro/basic_04_c3_utf8.t       TESTS     TODO: Malformed UTF-8.
mro/dbic_c3_utf8.t           TESTS     Test results:
mro/next_NEXT.t              SIG       Exit signal is 11 SEGV
mro/vulcan_c3_utf8.t         TESTS     TODO: Malformed UTF-8.

The only thing that's suspicious is that op/write.t starts segfaulting instead of having a PLAN failure but I'm inclined to treat that as jitter for the moment.

**Comment by rurban** [comment]
The code and idea looks good, but there are two severe errors. See my comments in the commit.

**Comment by toddr** [comment]
PR #286 resolved this when it was merged to master.
