### ISSUE TITLE
 undefined reference to `main'

### ISSUE THREAD

**Issue by Prajithp** [rurban/perl-compiler#339]
Any idea why I'm getting this?

root@sip [~]# /usr/local/cpanel/3rdparty/perl/514/bin/perlcc --shared Test.pm
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: ld returned 1 exit status

**Comment by rurban** [comment]
Yes. Try the options `-v5 -S` to enhance verbosity and keep the intermediate source files.
```
cript/perlcc -v5 -S --shared t/Test.pm
script/perlcc: Compiling t/Test.pm
script/perlcc: Writing C on Test.pm.c
script/perlcc: Calling /usr/local/bin/perl5.14.4-nt -MO=C,-m,,-Dsp,-v,-oTest.pm.c t/Test.pm
script/perlcc: Calling ccache gcc-mp-5  -fno-common -DPERL_DARWIN -m64 -mssse3 -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -I/opt/local/include  -I/usr/local/lib/perl5/5.14.4/darwin/CORE  -o ./t/Test Test.pm.c     -flat_namespace -fstack-protector -L/usr/local/lib -L/opt/local/lib  -L/usr/local/lib/perl5/5.14.4/darwin/CORE -lperl -ldl -lm -lutil -lc
gcc-mp-5: error: Test.pm.c: No such file or directory
```
The problem is that `.pm` implies `-m`, i.e. compiling to a module, but the empty `,,` option makes the -o option to be skipped. That's a perlcc bug.

`-m` is not yet supported. Use a `.pl` file.

**Comment by rurban** [comment]
See branch `pccmodule` for the start of preliminary module support. XS functions are not yet registered there.

**Comment by Prajithp** [comment]
Thanks Ruban for the clarification. I have installed perl-compiler from pccmodule branch, but now i'm getting different error.
```
 root@sip [~/perl-compiler]# ./blib/script/perlcc  -m --shared Test.pm
pccoaLVB.c: In function ‘boot_Test’:
pccoaLVB.c:319: error: too few arguments to function ‘perl_init’
pccoaLVB.c:327: error: incompatible types when assigning to type ‘struct OP *’ from type ‘OP’
```
```
root@sip [~/perl-compiler]# ./blib/script/perlcc  -m --staticxs Test.pm
pccJpY5A.c: In function ‘boot_Test’:
pccJpY5A.c:319: error: too few arguments to function ‘perl_init’
pccJpY5A.c:327: error: incompatible types when assigning to type ‘struct OP *’ from type ‘OP’
```

**Comment by rurban** [comment]
As I said, you cannot compiles single modules to shared libs yet. You need a .pl script, which uses this module and compile it to an executable.

**Comment by Prajithp** [comment]
Thanks Ruban.

 Thanks for the wonderful project.

**Comment by Prajithp** [comment]
Also, kindly let us know when it ready to use/

**Comment by rurban** [comment]
I cannot promise that it will be in the next release on Dec 5. Probably in February or so.
