### ISSUE TITLE
utf8_heavy can be reloaded during run time

### ISSUE THREAD

**Issue by atoomic** [rurban/perl-compiler#364]
Difficult to provide a single one liner here for now, but if during compilation we load utf8_heavy.pl, like in PMOP::Save, then if during runtime we lazy load a module which requires utf8_heavy.pl this will result in a warning like

```
Subroutine _loose_name redefined at /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/5.22.1/utf8_heavy.pl line 16.
````

This shows that we reload utf8_heavy whereas we should not.
After investigation this is coming from the fact that we save utf8 before utf8_heavy.
Simply fixing the order in which we walk the packages fixes it.

Potentially same problem with bytes_heavy.pl

**Comment by rurban** [comment]
Thanks for the fix
