### ISSUE TITLE
Data::Alias: panic: unimplemented op custom (#392) called

### ISSUE THREAD

**Issue by sten22** [rurban/perl-compiler#372]
perl 5.22.3c
test script:
```
use Data::Alias;

my $x = 3;
alias my $y = $x;

warn $y;
```

expected output:
```
$ perl bc-alias.pl
3 at bc-alias.pl line 6.
```

compiled output:
```
./bc-alias
panic: unimplemented op custom (#392) called at bc-alias.pl line 4.
```

**Comment by rurban** [comment]
This is an expected error. I will unfortunately not add custom Data::Alias support, as Data::Alias is now deprecated. core 5.22 added their own aliasing feature, with a different syntax, different to Data::Alias and different to perl6.
