### ISSUE TITLE
Floating precision issue with NVs

### ISSUE THREAD

**Issue by atoomic** [rurban/perl-compiler#373]
Floating precision issue with NVs

Notice this issue with the new unit tests added to t/op/64bitint.t in v5.24.
But this is not a 5.24 specific issue, same problem with earlier versions.

Note that the current perl is not compiled with 'uselongdouble' support
```
> perl -MConfig -E 'say $Config{uselongdouble}'
```

Oneliner to reproduce the error:
```
> perl -e 'my $a = 1<<1; my $b = 1 << 63; print (  $a * $b == 18446744073709551616 ? 1 : 0 )'
1
> perlcc -S -r -e 'my $a = 1<<1; my $b = 1 << 63; print (  $a * $b == 18446744073709551616 ? 1 : 0 )'
0
```

After inspecting the c code we are storing the NV value as this with 16 precision

```
 Static XPVNV xpvnv_list[1] = {

     { Nullhv, {0}, 0, {0}, {0}, {1.844674407370955e+19} }, /* xpvnv_list[0]  */ # 16

 };
```

By increasing the precision to 1 when storing it in C, we are fixing the precision issue.
So I wonder if we should not increase the precision by 1. (also tried with 18 and works fine)

```

    Static XPVNV xpvnv_list[1] = {

     { Nullhv, {0}, 0, {0}, {0}, {1.8446744073709552e+19} }, /* xpvnv_list[0]  */ # 17

 };
```

Suggested patch (but do not know if the value for uselongdouble should be greater than 18 or not)

```diff
diff --git a/lib/B/C.pm b/lib/B/C.pm
index 18a3cd0..090375c 100644
--- a/lib/B/C.pm
+++ b/lib/B/C.pm
@@ -1263,7 +1263,7 @@ sub nvx ($) {
   my $ll = $Config{d_longdbl} ? "LL" : "L";
   if ($nvgformat eq 'g') { # a very poor choice to keep precision
     # on intel 17-18, on ppc 31, on sparc64/s390 34
-    $nvgformat = $Config{uselongdouble} ? '.17Lg' : '.16g';
+    $nvgformat = $Config{uselongdouble} ? '.18Lg' : '.17Lg';
   }
   my $sval = sprintf("%${nvgformat}%s", $nvx, $nvx > $dblmax ? $ll : "");
   if ($nvx < -$dblmax) {
```

**Comment by rurban** [comment]
We really need to probe for printf %a and use it. (hex literals)

**Comment by toddr** [comment]
I'm fuzzy on this but it looks like support for this wasn't added until 5.22.0

"Floating point parsing has been improved

Parsing and printing of floating point values has been improved.

As a completely new feature, hexadecimal floating point literals (like 0x1.23p-4) are now supported, and they can be output with printf "%a". See "Scalar value constructors" in perldata for more details."

**Comment by rurban** [comment]
Yes, but we are talking about %a support in C, and don't care about hexfloats in perl.
Our C compiler needs to parse that to be able to dump all float bits. Or use a union trick.

**Comment by rurban** [comment]
I'll add a new ticket for %a (probing and dumping hexfloats).
