### ISSUE TITLE
Perl error from cc_harness (B-C-1.54) when using MSVC

### ISSUE THREAD

**Issue by jkahrman** [rurban/perl-compiler#381]
While attempting to install B-C-1.54 into a perl 5.20.2 on Windows using MSVC, the tests encounter 160 instances of:

Undefined subroutine &main::opt called at script/cc_harness line 74.

Lines 74 and 77 reference the subroutine 'opt', but I can't find any reference in recent versions of Config or ExtUtils::Embed that provide this method.

**Comment by rurban** [comment]
This is already fixed in the latest experimental releases on cpan, in master and in the versions included with cperl. (where we smoke windows also)

cpan RURBAN/B-C-1.54_08.tar.gz
