### ISSUE TITLE
B::C generates code requiring a gcc extension outside the C standard

### ISSUE THREAD

**Issue by jkahrman** [rurban/perl-compiler#382]
While attempting to install B-C-1.54 into a perl 5.20.2 on Windows using MSVC, the tests encounter more than 2000 instances of: 
`
error C2036: 'void *' : unknown size`
Failed 81/112 test programs. 353/821 subtests failed.

According to postings on stackoverflow, this error is due to the use of a gcc extension outside the C standard, so MSVC cannot compile it.

http://stackoverflow.com/questions/1864352/pointer-arithmetic-when-void-has-unknown-size/1864369#1864369
http://stackoverflow.com/questions/1864956/byte-precision-pointer-arithmetic-in-c-when-sizeofchar-1
https://gcc.gnu.org/onlinedocs/gcc-4.4.2/gcc/Pointer-Arith.html#Pointer-Arith

**Comment by rurban** [comment]
This is already fixed in the latest experimental releases on cpan and in master.

cpan RURBAN/B-C-1.54_08.tar.gz
