### ISSUE TITLE
Bug in B::C::B::RV::save generating 'ptr_undef' when d_c99_variadic_macros not defined

### ISSUE THREAD

**Issue by jkahrman** [rurban/perl-compiler#383]
There's a precedence bug in B::C::B::RV::save at the ternary operator generating the 'ptr_undef' line when d_c99_variadic_macros are not defined. This results in invalid C:

`	{ ptr_undef, 1, 0x801, {} }, /* sv_list[114]  */`

instead of 

`	{ ptr_undef, 1, 0x801, {0 /* &sv_list[89] */} }, /* sv_list[114]  */`

```
lib/B/C.pm
3705c3705
<                            ($C99 and is_constant($rv) ? ".svu_rv=$rv" : "0 /* $rv */")));
---
>                            ($C99 && is_constant($rv) ? ".svu_rv=$rv" : "0 /* $rv */")));
```

**Comment by rurban** [comment]
Fixed with 3f9aa5153db2037a17b4d7709a0ccfd7bfad736e
