### ISSUE TITLE
UTF-8 in source cause utf8.pm to dynamically reload

### ISSUE THREAD

**Issue by sten22** [rurban/perl-compiler#417]
Simple test case(reduced from Net::Whois::Raw):
```
$ cat utf8-dynaloader2.pl
use utf8;
m/Доменное имя .*? не зарегистрировано/i;
print "ok\n";

$ /build/cperl/bin/perlcc --staticxs --static -S -v4 -uutf8 utf8-dynaloader2.pl
/build/cperl/bin/perlcc: Writing C on utf8-dynaloader2.c
/build/cperl/bin/perlcc: Calling /build/cperl/bin/cperl -MO=C,-staticxs,-uutf8,-outf8-dynaloader2.c utf8-dynaloader2.pl
/build/cperl/bin/perlcc: Calling cc  -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2  -I/build/cperl/lib/5.26.2/x86_64-linux/CORE  -o "./utf8-dynaloader2" "utf8-dynaloader2.c"  -DSTATICXS -Wl,-E  -fstack-protector-strong -L/usr/local/lib /build/cperl/lib/5.26.2/x86_64-linux/auto/Config/Config.a -L/build/cperl/lib/5.26.2/x86_64-linux/CORE /build/cperl/lib/5.26.2/x86_64-linux/CORE/libperl.a -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc -lperl

$ mv /build/cperl /build/cperl_; ./utf8-dynaloader2; mv /build/cperl_ /build/cperl
Can't locate utf8.pm in @INC (you may need to install the utf8 module) (@INC contains: /build/cperl/lib/site_cperl/5.26.2/x86_64-linux /build/cperl/lib/site_cperl/5.26.2 /build/cperl/lib/5.26.2/x86_64-linux /build/cperl/lib/5.26.2).
BEGIN failed--compilation aborted.
```

**Comment by rurban** [comment]
works fine for me with 5.24 and 5.26 on darwin.

**Comment by sten22** [comment]
note that you need to hide perl directory(e.g. move it)

**Comment by rurban** [comment]
I'm working with the installed perl. There's no perl srcdir around. I guess you have a bad dir in your config, still pointing to your srcdir.

**Comment by sten22** [comment]
I'm not sure what do yo mean by srcdir, I try to run compiled binary in perl-less environment - include all modules and make binary completely portable

Everything works fine if you don't use utf8 strings in script source, but if you use then for some reason utf8.pm will loaded from runtime through ```@INC```, strace output:
```
stat("/build/cperl/lib/site_cperl/5.26.2/x86_64-linux/utf8.pmc", 0x7fffd860a170) = -1 ENOENT (No such file or directory)
stat("/build/cperl/lib/site_cperl/5.26.2/x86_64-linux/utf8.pm", 0x7fffd860a170) = -1 ENOENT (No such file or directory)
stat("/build/cperl/lib/site_cperl/5.26.2/utf8.pmc", 0x7fffd860a170) = -1 ENOENT (No such file or directory)
stat("/build/cperl/lib/site_cperl/5.26.2/utf8.pm", 0x7fffd860a170) = -1 ENOENT (No such file or directory)
stat("/build/cperl/lib/5.26.2/x86_64-linux/utf8.pmc", 0x7fffd860a170) = -1 ENOENT (No such file or directory)
stat("/build/cperl/lib/5.26.2/x86_64-linux/utf8.pm", 0x7fffd860a170) = -1 ENOENT (No such file or directory)
stat("/build/cperl/lib/5.26.2/utf8.pmc", 0x7fffd860a170) = -1 ENOENT (No such file or directory)
stat("/build/cperl/lib/5.26.2/utf8.pm", 0x7fffd860a170) = -1 ENOENT (No such file or directory)
write(2, "Can't locate utf8.pm in @INC (yo"..., 268Can't locate utf8.pm in @INC (you may need to install the utf8 module) (@INC contains: /build/cperl/lib/site_cperl/5.26.2/x86_64-linux /build/cperl/lib/site_cperl/5.26.2 /build/cperl/lib/5.26.2/x86_64-linux /build/cperl/lib/5.26.2).
BEGIN failed--compilation aborted.
) = 268
```

**Comment by sten22** [comment]
update: this relate for regex only

**Comment by rurban** [comment]
Do you see the error now? You removed the @INC for your perl.
/build/cperl/lib/5.26.2 is needed. Without @INC compilation and run-time will fail. 
In this case run-time, because require utf8 is deferred for m//i regexes with unicode strings.

**Comment by sten22** [comment]
I don't removed @INC, I move compiled binary to another machine without perl

**Comment by sten22** [comment]
I got another error, even on machine with cperl installed:
```
$ cat utf8-dynaloader2.pl
use Data::Dumper;
use utf8;
INIT { warn Dumper \%INC };
m/Доменное имя .*? не зарегистрировано/i;
print "ok\n";
```

```
$ ./utf8-dynaloader2
Not a CODE reference at /build/cperl/lib/5.26.2/x86_64-linux/re.pm line 89.
Compilation failed in require at /build/cperl/lib/5.26.2/utf8_heavy.pl line 4.
BEGIN failed--compilation aborted at /build/cperl/lib/5.26.2/utf8_heavy.pl line 4.
Compilation failed in require at /build/cperl/lib/5.26.2/utf8.pm line 60.
```

**Comment by constantined** [comment]
The problem is that loading utf8 in runtime makes static linking completely useless.
On Windows utf8.pm loads re.pm, which loads re.dll, which loads cperl*.dll. So static linking requires two cperl libraries: static and dynamic.

**Comment by sten22** [comment]
After investigation with @constantined we found that load_utf8_heavy is never called due to https://github.com/perl11/cperl/blob/master/cpan/B-C/lib/B/C.pm#L9013

It is always return from here https://github.com/perl11/cperl/blob/master/cpan/B-C/lib/B/C.pm#L4067
Everything works fine if comment out this line, but may be there are more correct patch

**Comment by rurban** [comment]
You mean after you comment out L9013?

**Comment by constantined** [comment]
L4067. Same effect if you add "delete $savINC{"utf8_heavy.pl"};" after L9013

**Comment by rurban** [comment]
Well --staticxs and a static libperl will load re.dll, but not the dynamic libperl, because this does not exist.
You can enforce preloading all XS you will encounter dynamically.
And you still got this problem because you removed the path for the dynamic modules. 
Either convert everything to static or keep the runtime modules.
It's a lot of work, I know.

**Comment by sten22** [comment]
Everything is already converted to static and linked:
```
/build/v8-patches/bin/perlcc: Calling cc  -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2  -I/build/cperl/lib/5.26.2/x86_64-linux/CORE  -o "./utf8-dynaloader2" "utf8-dynaloader2.c"  -DSTATICXS -Wl,-E  -fstack-protector-strong -L/usr/local/lib /build/cperl/lib/5.26.2/x86_64-linux/auto/Data/Dumper/Dumper.a /build/cperl/lib/5.26.2/x86_64-linux/auto/re/re.a /build/cperl/lib/5.26.2/x86_64-linux/auto/Config/Config.a /build/cperl/lib/5.26.2/x86_64-linux/auto/Data/Dumper/Dumper.a /build/cperl/lib/5.26.2/x86_64-linux/auto/re/re.a -L/build/cperl/lib/5.26.2/x86_64-linux/CORE /build/cperl/lib/5.26.2/x86_64-linux/CORE/libperl.a -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc -lperl
```

The problem is with ```$INC{"utf8_heavy.pl");```, in this case it exists in compile time and ```load_utf8_heavy``` which should save ```SWASHNEW``` is never called. The patch is simple, do you accept pull requests?

**Comment by rurban** [comment]
You still rely on DynaLoader and run-time loading of certain optional parts, like the unicode tables.
Which is what utf8_heavy.pl handles. You can force a static utf8_heavy.pl by adding all these also at compile-time, then your error will disappear. But the unicode tables are still plain-old perl, (and extremely slow), and perl itself does not support embedded unicode tables. Everything is run-time loaded from some unicore file.
cperl will sometime soon. But it's not high-priority, since I'm not working for cPanel anymore.
See the code by yourself.
