### ISSUE TITLE
Removing/correcting web site reference

### ISSUE THREAD

**Issue by trantor** [rurban/perl-compiler#421]
I've noticed how 
https://github.com/rurban/perl-compiler/blob/c9f9582cd2831f7633af0e8b82c5c4d28c96a334/README#L7
`http://www.perl-compiler.org/` appears to host a web site talking about food supplements in Japanese.

There's also the `search.cpan.org` -> `metacpan.org` change. Just as a mention.

Minor stuff.

**Comment by rurban** [comment]
Oh my, they didn't prolong the DNS. Thanks.
Regarding the search.cpan.org -> metacpan.org: I'll ignore that.
