### ISSUE TITLE
B::C ignores ISA

### ISSUE THREAD

**Issue by constantined** [rurban/perl-compiler#426]
testcase:
```perl
package Net::DNS::Domain;
sub new { warn "new" };

package Net::DNS::DomainName1035;
our @ISA = qw(Net::DNS::Domain);

package main;

Net::DNS::DomainName1035->new();
```
Compiled binary dies with `Can't locate object method "new" via package "Net::DNS::DomainName1035"`

**Comment by rurban** [comment]
Can you try adding a sub to the subclass? There was a limitation with empty classes in the walker as far as I remember.

**Comment by a-parser** [comment]
Adding a sub doesn't help, the problem even worse, the compiler doesn't see our ```@ISA``` = (...) during CHECK phase:

```
package B::isabugcompiler;
sub compile {
	warn "compile";
	warn "ISA: ", @Net::DNS::DomainName1035::ISA;
}

1;
```

```
perl -I. -MO=isabugcompiler isa-bug.pl
ISA: 
```


The workaround is to move ```@ISA``` initialization to BEGIN phase:
```
use base 'Net::DNS::Domain';
```

But this is impossible because a huge amount of code already use direct ```@ISA``` manipulation

**Comment by constantined** [comment]
Sorry, it was invalid bug report. See #427
