### ISSUE TITLE
nmake test failing in B-C-1.57 module with Perl 5.36 ("G_ARRAY" is not exported by the B module)

### ISSUE THREAD

**Issue by harithecreator** [rurban/perl-compiler#442]
Hi Team,
I am getting below errors while running nmake test in B-C-1.57 module. G_ARRAY is deprecated in perl 5.36 and replaced with G_LIST. will there be new release of B-C module with G_LIST changes? or can you please suggest how can i proceed on this issue?

error snippet:
=========
t\cc_last.t ....... "G_ARRAY" is not exported by the B module
Can't continue after import errors at C:/this_is_a_fake_path/this_is_a_fake_path/this_is_a_fake_path/this_is_a_fake_path/this_is_a_fake_path/this_is_a_fake_path/this_is_a_fake_path/lib/B.pm line 16.
BEGIN failed--compilation aborted at C:\Harish\Modules\B-C-1.57\blib\lib/B/CC.pm line 316.
Compilation failed in require at t\cc_last.t line 29.
BEGIN failed--compilation aborted at t\cc_last.t line 29.
t\cc_last.t ....... Dubious, test returned 2 (wstat 512, 0x200)
Failed 3/3 subtests

Thanks & Regards,
Harish

**Comment by harithecreator** [comment]
Thanks @rurban.. I got the changes from branch 536 to make B-C module work in my local.. is there any chance for official new release of B-C module in near future with these G_ARRAY deprecated changes?

**Comment by rurban** [comment]
harithecreator ***@***.***> schrieb am Di., 27. Sep. 2022,
15:11:

> Thanks @rurban <https://github.com/rurban>.. I got the changes from
> branch 536 to make B-C module work in my local.. is there any chance for
> official new release of B-C module in near future with these G_ARRAY
> deprecated changes?
>

Not so fast, because perl5.36 is officially unsupported

**Comment by rurban** [comment]
This particular problem was fixed, but there are many more still.
