### ISSUE TITLE
swash_init: utf8_heavy imports Carp unnecessarily

### ISSUE THREAD

**Issue by rurban** [rurban/perl-compiler#63]
Original [issue 61](https://code.google.com/p/perl-compiler/issues/detail?id=61) created by rurban on 2011-02-28T17:48:17.000Z:

Since 5.13.10 without -fno-fold the mandatory swash_init(&quot;utf8&quot;) compiles &amp;utf8::AUTOLOAD and then it imports Carp.

  sub AUTOLOAD {
    require &quot;utf8_heavy.pl&quot;;
    goto &amp;$AUTOLOAD if defined &amp;$AUTOLOAD;
    require Carp;
    Carp::croak(&quot;Undefined subroutine $AUTOLOAD called&quot;);
  }

We can safely assume utf8_heavy.pl to be added, and can get rid 
of the failure case to require Carp.
This will save a lot of speed and memory, even when we need utf8 e.g. to do case-folding (m//i).

We could think of generalizing the pattern
  sub AUTOLOAD {
    require &quot;...&quot;;
    goto &amp;$AUTOLOAD if defined &amp;$AUTOLOAD;
    #... skipped
  }
skipping everything after the goto if compile-time AUTOLOAD succeeds.

**Comment by atoomic** [comment]
added the test to testc.sh (pending MR https://github.com/rurban/perl-compiler/pull/311 )
looks fine, we can close this one
